# Run this playbook with this command: ansible-playbook --connection=localhost --ask-become-pass development-tools.yml

---
- name: Install Development Tools such as language frameworks and debuggers.
  hosts: localhost
  tasks:
    - name: Install tools
      ansible.builtin.apt:
        pkg:
        - gdb
        - gir1.2-gmenu-3.0
        - gnome-tweaks
        - unzip
        - dconf-cli
        - cmake
        - freeglut3-dev
        - libxrandr-dev
        - python3-pip
        - libgl1-mesa-dev
        - libegl1-mesa-dev
        - libwebkit2gtk-4.0-dev
        - build-essential
        - curl
        - wget
        - file
        - libssl-dev
        - libgtk-4-dev
        - libayatana-appindicator3-dev
        - librsvg2-dev
        - dconf-cli
        - cargo
        - texlive-full
        - libncurses-dev
      become: yes
