# Run this playbook with this command: ansible-playbook --connection=localhost --ask-become-pass gaming-apps.yml

---
- name: Install Gaming Software
  hosts: localhost
  tasks:
    - name: Install Discord
      apt:
        deb: https://discord.com/api/download?platform=linux&format=deb
      become: yes
    - name: Install Steam
      apt:
        deb: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
      become: yes


      